//! `resolve_market` / `lock_market` — settling a market against TxLINE's
//! on-chain, Merkle-anchored score data.
//!
//! Rule: resolution MUST be impossible unless TxLINE's own `validate_stat`
//! instruction succeeds. TxLINE is the judge; this program (and its
//! keeper) never is. Concretely: `resolve_market` CPIs into
//! `validate_stat` and propagates any error from it with `?` — a failed
//! or malformed proof aborts the whole transaction, `market` is never
//! touched, and there is no code path that marks a market `Resolved`
//! without that CPI having returned `Ok(())` first.
//!
//! ```text
//! keeper                verifibet::resolve_market         txline::validate_stat
//!   |                            |                                 |
//!   |--(outcome, ts, proof)----->|                                 |
//!   |                            |--guards: status, kickoff, ------|
//!   |                            |  outcome<3, stat period==100    |
//!   |                            |                                 |
//!   |                            |--CPI: validate_stat(ts, ------->|
//!   |                            |    fixture_summary, proofs,     |--checks proof against
//!   |                            |    predicate(outcome), stat_a,  |  daily_scores_merkle_roots
//!   |                            |    stat_b=away, op=Subtract)    |  (TxLINE's own root, not ours)
//!   |                            |                                 |
//!   |                            |<--Ok(()) or Err (reverts all)---|
//!   |                            |                                 |
//!   |                            |--on Ok: market.status=Resolved  |
//!   |                            |  market.outcome, resolved_at,   |
//!   |                            |  proof_hash = sha256(...)       |
//!   |                            |  emit!(MarketResolved)          |
//!   |<---------------------------|                                 |
//! ```
//!
//! ## Typed CPI
//!
//! `crate::txline_validate` is generated by `declare_program!` from
//! `anchor/idls/txline_validate.json` — a trimmed copy of the fetched
//! devnet IDL (`anchor/idls/txline.json`) containing only `validate_stat`
//! and its argument types. See the comment above `declare_program!` in
//! `lib.rs` for why it's trimmed (two real `declare_program!` codegen bugs
//! in the untrimmed IDL, confirmed with `cargo expand`, not guessed).
//!
//! `validate_stat`'s real signature (read from the generated module, not
//! assumed) is far richer than a flat `stat_value` + `merkle_proof`:
//!
//! ```text
//! validate_stat(
//!     ts: i64,
//!     fixture_summary: ScoresBatchSummary,
//!     fixture_proof: Vec<ProofNode>,
//!     main_tree_proof: Vec<ProofNode>,
//!     predicate: TraderPredicate,
//!     stat_a: StatTerm,
//!     stat_b: Option<StatTerm>,
//!     op: Option<BinaryExpression>,
//! ) -> Result<()>
//! ```
//!
//! It proves `(stat_a [op stat_b])` against `predicate` via a three-level
//! Merkle proof (stat -> fixture's event sub-tree -> TxLINE's daily root),
//! and — confirmed from the generated code, this deployed version has no
//! `returns` field — signals failure purely by returning `Err` (reverting
//! the whole CPI), not by returning a queryable `false`. There's nothing
//! to separately check beyond propagating the `Result`.
//!
//! `resolve_market` doesn't expose that full generality to the caller.
//! Letting the keeper supply an arbitrary `predicate` independently of
//! `outcome` would reopen exactly the hole this whole design exists to
//! close (the keeper claiming one outcome while proving something else) —
//! so this program always sets `stat_a` = the home team's goals,
//! `stat_b` = the away team's, `op` = `Subtract`, and derives `predicate`
//! deterministically from `outcome` (`GreaterThan 0` / `EqualTo 0` /
//! `LessThan 0` for home / draw / away). The keeper only supplies the two
//! `StatTerm`s (each with its own Merkle proof) and the `outcome` they
//! claim those terms prove.
//!
//! ## Trust boundary that's still real after all of the above
//!
//! `ScoreStat.key: u32` is an opaque TxODDS-internal code — nothing in the
//! IDL documents which key means "home team goals" vs "away team goals".
//! The Merkle proof cryptographically guarantees the *value* for whatever
//! key was requested is real; it does not guarantee the keeper requested
//! the *right* keys. `require!(stat_home.stat_to_prove.period == 100 ...)`
//! below (TxODDS's documented code for a finalised full-time result, see
//! NOTES.md) stops a keeper from proving an earlier-period score (e.g.
//! half-time) and passing it off as final, but a keeper that swaps which
//! key is "home" and which is "away" is not caught by any on-chain check
//! — TxLINE has no on-chain concept of "home" vs "away" for a stat key,
//! only VERIFIBET's own `Market.home`/`Market.away` do, and those aren't
//! cryptographically tied to TxODDS's stat key registry. This is the one
//! place `market.authority` is still trusted, not just TxLINE.

use anchor_lang::prelude::*;

use crate::errors::VerifibetError;
use crate::instructions::common;
use crate::state::{Market, MarketStatus, MARKET_SEED};
use crate::txline_validate::{
    self,
    program::Txoracle,
    types::{BinaryExpression, Comparison, ProofNode, ScoresBatchSummary, StatTerm, TraderPredicate},
};

/// TxODDS's documented code for a finalised, full-time result — set on
/// score records with `action=game_finalised` (regulation, extra time,
/// penalties, and abandoned matches all use this same code). See
/// `documentation/examples/onchain-validation.mdx` in
/// `github.com/txodds/tx-on-chain`.
const FULL_TIME_PERIOD: i32 = 100;

/// One unix day, in milliseconds — TxLINE's `ts` argument and the
/// `daily_scores_roots` PDA's epoch-day seed are both in these units
/// (confirmed against the reference `epochDay = Math.floor(targetTs /
/// (24 * 60 * 60 * 1000))`), unlike the rest of this program's
/// unix-seconds convention (see CLAUDE.md).
const MS_PER_DAY: i64 = 24 * 60 * 60 * 1000;

#[derive(Accounts)]
#[instruction(outcome: u8, ts: i64)]
pub struct ResolveMarket<'info> {
    #[account(constraint = authority.key() == market.authority @ VerifibetError::Unauthorized)]
    pub authority: Signer<'info>,

    #[account(
        mut,
        seeds = [MARKET_SEED, market.fixture_id.to_le_bytes().as_ref()],
        bump = market.bump,
    )]
    pub market: Account<'info, Market>,

    /// `Program<'info, T>` already enforces this is exactly TxLINE's
    /// deployed program (`txline_validate::ID`, embedded from the IDL's
    /// own `address` field) — no other program can be substituted here.
    pub txline_program: Program<'info, Txoracle>,

    /// CHECK: owned by `txline_program`, not us, hence `UncheckedAccount`
    /// rather than a typed `Account<'info, _>` — we have no (and shouldn't
    /// invent any) view into its internal layout; `validate_stat` is the
    /// only thing that reads it. What *is* checked here: the `seeds` +
    /// `seeds::program` constraint below re-derives this as TxLINE's daily
    /// Merkle-root PDA for the epoch day implied by `ts`, rather than
    /// trusting whatever account the caller passes — TxLINE's own
    /// `validate_stat` independently re-checks this PDA too, but this
    /// closes the gap before a mismatched-day account even reaches the
    /// CPI. `validate_stat`'s own IDL entry has exactly this one account,
    /// confirmed via `cargo expand` — not "config/root PDAs" plural, just
    /// this one.
    ///
    /// `.clamp(0, u16::MAX as i64)` (security audit finding, SECURITY.md
    /// §5): `ts` is keeper-supplied and signed i64; an unclamped `ts /
    /// MS_PER_DAY` on a negative or absurdly large `ts` would silently
    /// truncate on the `as u16` cast instead of erroring. Not independently
    /// exploitable (a wrapped epoch day just fails to match any account
    /// TxLINE actually maintains, and `validate_stat` re-derives the same
    /// PDA from the same `ts` independently), but relying on that instead
    /// of well-defined arithmetic here isn't the "checked arithmetic"
    /// standard the rest of this program holds to. Clamping makes the
    /// seeds expression itself well-defined for every possible `ts`
    /// without needing a `require!` that Anchor would evaluate too late
    /// anyway (Accounts constraints run before the handler body).
    #[account(
        seeds = [
            b"daily_scores_roots",
            &((ts / MS_PER_DAY).clamp(0, u16::MAX as i64) as u16).to_le_bytes()
        ],
        bump,
        seeds::program = txline_program.key(),
    )]
    pub daily_scores_merkle_roots: UncheckedAccount<'info>,
}

#[derive(Accounts)]
pub struct LockMarket<'info> {
    #[account(constraint = authority.key() == market.authority @ VerifibetError::Unauthorized)]
    pub authority: Signer<'info>,

    #[account(
        mut,
        seeds = [MARKET_SEED, market.fixture_id.to_le_bytes().as_ref()],
        bump = market.bump,
    )]
    pub market: Account<'info, Market>,
}

#[event]
pub struct MarketResolved {
    pub market: Pubkey,
    pub fixture_id: u64,
    pub outcome: u8,
    pub proof_hash: [u8; 32],
}

pub fn lock_market(ctx: Context<LockMarket>) -> Result<()> {
    require!(
        ctx.accounts.market.status == MarketStatus::Open,
        VerifibetError::MarketNotOpen
    );
    ctx.accounts.market.status = MarketStatus::Locked;
    Ok(())
}

#[allow(clippy::too_many_arguments)]
pub fn resolve_market(
    ctx: Context<ResolveMarket>,
    outcome: u8,
    ts: i64,
    fixture_summary: ScoresBatchSummary,
    fixture_proof: Vec<ProofNode>,
    main_tree_proof: Vec<ProofNode>,
    stat_home: StatTerm,
    stat_away: StatTerm,
) -> Result<()> {
    common::require_open_or_locked(ctx.accounts.market.status)?;
    require!(
        Clock::get()?.unix_timestamp > ctx.accounts.market.kickoff_ts,
        VerifibetError::KickoffNotPassed
    );
    require!(outcome < 3, VerifibetError::InvalidOutcome);

    // "FULL-TIME RESULT" is a requirement of this instruction, not just of
    // whatever the keeper happened to submit — the CPI below proves the
    // submitted stat *values* are real, it says nothing about which
    // moment in the match they're from. Without this, a keeper could
    // prove a half-time score and resolve the market on it.
    require!(
        stat_home.stat_to_prove.period == FULL_TIME_PERIOD
            && stat_away.stat_to_prove.period == FULL_TIME_PERIOD,
        VerifibetError::InvalidStatProof
    );
    require!(
        stat_home.stat_to_prove.key != stat_away.stat_to_prove.key,
        VerifibetError::InvalidStatProof
    );

    // stat_home/stat_away are moved into the CPI call below; capture what
    // we still need for our own state afterward first. ScoresBatchSummary
    // is Copy, so `fixture_summary` itself is still usable after the CPI
    // call moves a copy of it — captured here anyway for clarity.
    let home_value = stat_home.stat_to_prove.value;
    let away_value = stat_away.stat_to_prove.value;
    let events_sub_tree_root = fixture_summary.events_sub_tree_root;

    let comparison = match outcome {
        0 => Comparison::GreaterThan, // home - away > 0 => home win
        1 => Comparison::EqualTo,     // home - away == 0 => draw
        _ => Comparison::LessThan,    // home - away < 0 => away win (outcome == 2, guarded above)
    };

    txline_validate::cpi::validate_stat(
        CpiContext::new(
            ctx.accounts.txline_program.to_account_info(),
            txline_validate::cpi::accounts::ValidateStat {
                daily_scores_merkle_roots: ctx
                    .accounts
                    .daily_scores_merkle_roots
                    .to_account_info(),
            },
        ),
        ts,
        fixture_summary,
        fixture_proof,
        main_tree_proof,
        TraderPredicate {
            threshold: 0,
            comparison,
        },
        stat_home,
        Some(stat_away),
        Some(BinaryExpression::Subtract),
    )?;

    // Only reachable if the CPI above returned Ok — see the module-level
    // doc comment for why that's the only way to reach here.
    let market = &mut ctx.accounts.market;
    market.outcome = outcome;
    market.status = MarketStatus::Resolved;
    market.resolved_at = Clock::get()?.unix_timestamp;

    // Preimage: fixture_id (LE u64) || outcome (u8) || home_value (LE i32)
    // || away_value (LE i32) || events_sub_tree_root (32 bytes) — commits
    // to the specific fixture, claimed outcome, and the exact proven
    // values + the Merkle root that anchors them, so this hash can be
    // independently re-derived and checked against TxLINE's own data
    // off-chain.
    let mut preimage = Vec::with_capacity(8 + 1 + 4 + 4 + 32);
    preimage.extend_from_slice(&market.fixture_id.to_le_bytes());
    preimage.push(outcome);
    preimage.extend_from_slice(&home_value.to_le_bytes());
    preimage.extend_from_slice(&away_value.to_le_bytes());
    preimage.extend_from_slice(&events_sub_tree_root);
    market.proof_hash = anchor_lang::solana_program::hash::hash(&preimage).to_bytes();

    emit!(MarketResolved {
        market: market.key(),
        fixture_id: market.fixture_id,
        outcome,
        proof_hash: market.proof_hash,
    });

    Ok(())
}

/// ## ⚠️ Manual fallback — contingency only, not part of the submission ⚠️
///
/// `resolve_market_attested` resolves a market with **no on-chain TxLINE
/// validation whatsoever**: it stores whatever `proof_hash` `authority`
/// supplies, verbatim, with zero cryptographic guarantee it corresponds
/// to anything real. It exists only as a documented contingency for a
/// scenario where TxLINE's devnet program is unreachable during the
/// judging window and there is no other way to resolve a market at all.
///
/// Compiled out of the default build entirely — `cfg(feature =
/// "manual-fallback")`, off by default, so it cannot ship in the
/// submission build by accident. Building with `--features
/// manual-fallback` is itself a signal this path is in play.
///
/// **If this instruction is ever actually used for a submitted market:**
/// the README MUST say so explicitly (which market, why, when), and the
/// frontend MUST independently verify the Merkle proof client-side
/// (against TxLINE's public off-chain API data) before trusting any
/// `Receipt` for that market — this instruction provides no on-chain
/// guarantee the resolution is correct, only that *an authority claimed
/// it*, which is exactly the thing this whole feature exists to avoid.
// Deliberately NOT nested in its own `pub mod attested { ... }`: Anchor
// 0.30.1's `#[program]` macro derives the expected `__client_accounts_*`
// support-module name from the *first* path segment of the `Context<...>`
// type argument, not the last — `Context<attested::ResolveMarketAttested>`
// made it look for `__client_accounts_attested` instead of
// `__client_accounts_resolve_market_attested` and failed to compile
// (confirmed empirically, not guessed). Flattening to a bare identifier
// here, re-exported the same way as every other instruction in this
// module, sidesteps that bug entirely.
#[cfg(feature = "manual-fallback")]
#[derive(Accounts)]
pub struct ResolveMarketAttested<'info> {
    #[account(constraint = authority.key() == market.authority @ VerifibetError::Unauthorized)]
    pub authority: Signer<'info>,

    #[account(
        mut,
        seeds = [MARKET_SEED, market.fixture_id.to_le_bytes().as_ref()],
        bump = market.bump,
    )]
    pub market: Account<'info, Market>,
}

#[cfg(feature = "manual-fallback")]
pub fn resolve_market_attested(
    ctx: Context<ResolveMarketAttested>,
    outcome: u8,
    proof_hash: [u8; 32],
) -> Result<()> {
    common::require_open_or_locked(ctx.accounts.market.status)?;
    require!(
        Clock::get()?.unix_timestamp > ctx.accounts.market.kickoff_ts,
        VerifibetError::KickoffNotPassed
    );
    require!(outcome < 3, VerifibetError::InvalidOutcome);

    let market = &mut ctx.accounts.market;
    market.outcome = outcome;
    market.status = MarketStatus::Resolved;
    market.resolved_at = Clock::get()?.unix_timestamp;
    market.proof_hash = proof_hash;

    emit!(MarketResolved {
        market: market.key(),
        fixture_id: market.fixture_id,
        outcome,
        proof_hash,
    });

    Ok(())
}
