[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
verifibet = "21yiVGnTjDN7vCyk6hBotqCnVwxnVVQj3PNGdzfxqK4Z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
